"""
DJ 스테이션용 선별된 노래 데이터
"""

STATION_CURATION = {
    "신나는 노래": [
        # 한국 가요
        {"title": "파이팅 해야지", "artist": "부석순"},
        {"title": "I AM", "artist": "아이브"},
        {"title": "한 페이지가 될 수 있게", "artist": "DAY6"},
        {"title": "질풍가도", "artist": "유정석"},
        {"title": "사건의 지평선", "artist": "윤하"},
        {"title": "아주 NICE", "artist": "세븐틴"},
        {"title": "빨간 맛", "artist": "레드벨벳"},
        {"title": "챔피언", "artist": "싸이"},
        {"title": "붉은 노을", "artist": "빅뱅"},
        {"title": "예술이야", "artist": "싸이"},
        {"title": "여행을 떠나요", "artist": "조용필"},
        {"title": "말하자면", "artist": "김성재"},
        # 팝송
        {"title": "Uptown Funk", "artist": "Bruno Mars"},
        {"title": "Shake It Off", "artist": "Taylor Swift"},
        {"title": "Happy", "artist": "Pharrell Williams"},
        {"title": "Can't Stop The Feeling!", "artist": "Justin Timberlake"},
        {"title": "Dynamite", "artist": "BTS"},
        {"title": "Sugar", "artist": "Maroon 5"},
        {"title": "We Will Rock You", "artist": "Queen"},
        {"title": "September", "artist": "Earth, Wind & Fire"},
    ],
    "우울할 때": [
        # 한국 가요
        {"title": "한숨", "artist": "이하이"},
        {"title": "야생화", "artist": "박효신"},
        {"title": "아이와 나의 바다", "artist": "아이유"},
        {"title": "흰수염고래", "artist": "YB"},
        {"title": "이름에게", "artist": "아이유"},
        {"title": "바람이 분다", "artist": "이소라"},
        {"title": "숨", "artist": "박효신"},
        {"title": "나의 사춘기에게", "artist": "볼빨간사춘기"},
        {"title": "스물다섯 스물하나", "artist": "자우림"},
        {"title": "사랑 못해", "artist": "엠씨더맥스"},
        {"title": "그대라는 시", "artist": "태연"},
        {"title": "미아", "artist": "아이유"},
        # 팝송
        {"title": "Fix You", "artist": "Coldplay"},
        {"title": "Someone Like You", "artist": "Adele"},
        {"title": "Glimpse of Us", "artist": "Joji"},
        {"title": "Easy On Me", "artist": "Adele"},
        {"title": "My Love", "artist": "Westlife"},
        {"title": "Let It Be", "artist": "The Beatles"},
        {"title": "Bridge Over Troubled Water", "artist": "Simon & Garfunkel"},
        {"title": "Creep", "artist": "Radiohead"},
    ],
    "달달한 노래": [
        # 한국 가요
        {"title": "Love Lee", "artist": "AKMU"},
        {"title": "선물", "artist": "멜로망스"},
        {"title": "벚꽃 엔딩", "artist": "장범준"},
        {"title": "우주를 줄게", "artist": "볼빨간사춘기"},
        {"title": "사랑은 늘 도망가", "artist": "임영웅"},
        {"title": "취중고백", "artist": "김민석"},
        {"title": "너의 의미", "artist": "아이유"},
        {"title": "아로하", "artist": "조정석"},
        {"title": "주저하는 연인들을 위해", "artist": "잔나비"},
        {"title": "두 사람", "artist": "성시경"},
        {"title": "좋아 좋아", "artist": "일기예보"},
        {"title": "다행이다", "artist": "이적"},
        # 팝송
        {"title": "Peaches", "artist": "Justin Bieber"},
        {"title": "Kiss Me More", "artist": "Doja Cat"},
        {"title": "Perfect", "artist": "Ed Sheeran"},
        {"title": "I'm Yours", "artist": "Jason Mraz"},
        {"title": "Just The Way You Are", "artist": "Bruno Mars"},
        {"title": "Double Take", "artist": "dhruv"},
        {"title": "At My Worst", "artist": "Pink Sweat$"},
        {"title": "Reality", "artist": "Jeff Bernat"},
    ],
    "운전할 때": [
        # 한국 가요
        {"title": "Hype Boy", "artist": "NewJeans"},
        {"title": "Seven", "artist": "정국"},
        {"title": "After LIKE", "artist": "아이브"},
        {"title": "건물 사이에 피어난 장미", "artist": "H1-KEY"},
        {"title": "Attention", "artist": "NewJeans"},
        {"title": "Love Dive", "artist": "아이브"},
        {"title": "Spicy", "artist": "aespa"},
        {"title": "뷰티풀", "artist": "크러쉬"},
        {"title": "Dolphin", "artist": "오마이걸"},
        {"title": "신호등", "artist": "이무진"},
        {"title": "Next Level", "artist": "aespa"},
        {"title": "View", "artist": "샤이니"},
        # 팝송
        {"title": "As It Was", "artist": "Harry Styles"},
        {"title": "Cruel Summer", "artist": "Taylor Swift"},
        {"title": "Stay", "artist": "The Kid LAROI"},
        {"title": "I Ain't Worried", "artist": "OneRepublic"},
        {"title": "Levitating", "artist": "Dua Lipa"},
        {"title": "Blinding Lights", "artist": "The Weeknd"},
        {"title": "Sunroof", "artist": "Nicky Youre"},
        {"title": "Watermelon Sugar", "artist": "Harry Styles"},
    ],
    "운동할 때": [
        # 한국 가요
        {"title": "Antifragile", "artist": "LE SSERAFIM"},
        {"title": "Super Shy", "artist": "NewJeans"},
        {"title": "손오공", "artist": "세븐틴"},
        {"title": "이브 프시케 그리고 푸른 수염의 아내", "artist": "LE SSERAFIM"},
        {"title": "Smoke", "artist": "다이나믹 듀오"},
        {"title": "특", "artist": "Stray Kids"},
        {"title": "Fast Forward", "artist": "전소미"},
        {"title": "Baggy Jeans", "artist": "NCT U"},
        {"title": "영웅", "artist": "NCT 127"},
        {"title": "ETA", "artist": "NewJeans"},
        {"title": "Baddie", "artist": "아이브"},
        {"title": "퀸카", "artist": "아이들"},
        # 팝송
        {"title": "Unholy", "artist": "Sam Smith"},
        {"title": "Flowers", "artist": "Miley Cyrus"},
        {"title": "Good 4 U", "artist": "Olivia Rodrigo"},
        {"title": "Industry Baby", "artist": "Lil Nas X"},
        {"title": "Bones", "artist": "Imagine Dragons"},
        {"title": "Physical", "artist": "Dua Lipa"},
        {"title": "Paint The Town Red", "artist": "Doja Cat"},
        {"title": "Believer", "artist": "Imagine Dragons"},
    ],
    "집중 할때": [
        # 한국 가요
        {"title": "밤편지", "artist": "아이유"},
        {"title": "비가 오는 날엔", "artist": "비스트"},
        {"title": "instagram", "artist": "DEAN"},
        {"title": "Rain", "artist": "태연"},
        {"title": "Square (2017)", "artist": "백예린"},
        {"title": "좋다고 말해", "artist": "볼빨간사춘기"},
        {"title": "와르르", "artist": "Colde"},
        {"title": "오래된 노래", "artist": "스탠딩 에그"},
        {"title": "금요일에 만나요", "artist": "아이유"},
        {"title": "커피한잔할래요", "artist": "폴킴"},
        {"title": "어떻게 이별까지 사랑하겠어", "artist": "AKMU"},
        {"title": "밤하늘의 별을", "artist": "경서"},
        # 팝송
        {"title": "comethru", "artist": "Jeremy Zucker"},
        {"title": "Paris in the Rain", "artist": "Lauv"},
        {"title": "Sunday Morning", "artist": "Maroon 5"},
        {"title": "Best Part", "artist": "Daniel Caesar"},
        {"title": "Don't Know Why", "artist": "Norah Jones"},
        {"title": "Put Your Records On", "artist": "Corinne Bailey Rae"},
        {"title": "Off My Face", "artist": "Justin Bieber"},
        {"title": "Youth", "artist": "Troye Sivan"},
    ],
    "이별 노래": [
        # 한국 가요
        {"title": "헤어지자 말해요", "artist": "박재정"},
        {"title": "보고 싶다", "artist": "김범수"},
        {"title": "좋니", "artist": "윤종신"},
        {"title": "어디에도", "artist": "엠씨더맥스"},
        {"title": "소주 한 잔", "artist": "임창정"},
        {"title": "체념", "artist": "빅마마"},
        {"title": "응급실", "artist": "izi"},
        {"title": "너를 만나", "artist": "폴킴"},
        {"title": "가시", "artist": "버즈"},
        {"title": "첫눈처럼 너에게 가겠다", "artist": "에일리"},
        {"title": "기억을 걷는 시간", "artist": "넬"},
        {"title": "사랑에 연습이 있었다면", "artist": "임재현"},
        # 팝송
        {"title": "Drivers License", "artist": "Olivia Rodrigo"},
        {"title": "Someone You Loved", "artist": "Lewis Capaldi"},
        {"title": "When I Was Your Man", "artist": "Bruno Mars"},
        {"title": "Stay With Me", "artist": "Sam Smith"},
        {"title": "Lose You To Love Me", "artist": "Selena Gomez"},
        {"title": "I'm Not The Only One", "artist": "Sam Smith"},
        {"title": "Un-Break My Heart", "artist": "Toni Braxton"},
        {"title": "Grenade", "artist": "Bruno Mars"},
    ],
    "잠 안 올때": [
        # 한국 가요
        {"title": "무릎", "artist": "아이유"},
        {"title": "스토커", "artist": "10CM"},
        {"title": "양화대교", "artist": "Zion.T"},
        {"title": "잘 자요", "artist": "Zion.T"},
        {"title": "서른 즈음에", "artist": "김광석"},
        {"title": "잊어야 한다는 마음으로", "artist": "김광석"},
        {"title": "12시 30분", "artist": "비스트"},
        {"title": "기억의 습작", "artist": "전람회"},
        {"title": "눈의 꽃", "artist": "박효신"},
        {"title": "거리에서", "artist": "성시경"},
        {"title": "바람기억", "artist": "나얼"},
        {"title": "미안해 널 미워해", "artist": "자우림"},
        # 팝송
        {"title": "pov", "artist": "Ariana Grande"},
        {"title": "Chandelier (Piano Ver.)", "artist": "Sia"},
        {"title": "All of Me", "artist": "John Legend"},
        {"title": "2002", "artist": "Anne-Marie"},
        {"title": "Thinking Out Loud", "artist": "Ed Sheeran"},
        {"title": "Honesty", "artist": "Pink Sweat$"},
        {"title": "City of Stars", "artist": "Ryan Gosling"},
        {"title": "Lost Stars", "artist": "Adam Levine"},
    ],
}
