"""
DJ 스테이션용 선별된 노래 데이터
"""

# 1. 느낌 별 스테이션 (기존 데이터)
MOOD_STATIONS = {
    "신나는 노래": [
        # 한국 가요
        {"title": "파이팅 해야지", "artist": "부석순"},
        {"title": "I AM", "artist": "아이브"},
        {"title": "한 페이지가 될 수 있게", "artist": "DAY6"},
        {"title": "질풍가도", "artist": "유정석"},
        {"title": "사건의 지평선", "artist": "윤하"},
        {"title": "아주 NICE", "artist": "세븐틴"},
        {"title": "빨간 맛", "artist": "레드벨벳"},
        {"title": "챔피언", "artist": "싸이"},
        {"title": "붉은 노을", "artist": "빅뱅"},
        {"title": "예술이야", "artist": "싸이"},
        {"title": "여행을 떠나요", "artist": "조용필"},
        {"title": "말하자면", "artist": "김성재"},
        # 팝송
        {"title": "Uptown Funk", "artist": "Bruno Mars"},
        {"title": "Shake It Off", "artist": "Taylor Swift"},
        {"title": "Happy", "artist": "Pharrell Williams"},
        {"title": "Can't Stop The Feeling!", "artist": "Justin Timberlake"},
        {"title": "Dynamite", "artist": "BTS"},
        {"title": "Sugar", "artist": "Maroon 5"},
        {"title": "We Will Rock You", "artist": "Queen"},
        {"title": "September", "artist": "Earth, Wind & Fire"},
    ],
    "우울할 때": [
        # 한국 가요
        {"title": "한숨", "artist": "이하이"},
        {"title": "야생화", "artist": "박효신"},
        {"title": "아이와 나의 바다", "artist": "아이유"},
        {"title": "흰수염고래", "artist": "YB"},
        {"title": "이름에게", "artist": "아이유"},
        {"title": "바람이 분다", "artist": "이소라"},
        {"title": "숨", "artist": "박효신"},
        {"title": "나의 사춘기에게", "artist": "볼빨간사춘기"},
        {"title": "스물다섯 스물하나", "artist": "자우림"},
        {"title": "사랑 못해", "artist": "엠씨더맥스"},
        {"title": "그대라는 시", "artist": "태연"},
        {"title": "미아", "artist": "아이유"},
        # 팝송
        {"title": "Fix You", "artist": "Coldplay"},
        {"title": "Someone Like You", "artist": "Adele"},
        {"title": "Glimpse of Us", "artist": "Joji"},
        {"title": "Easy On Me", "artist": "Adele"},
        {"title": "My Love", "artist": "Westlife"},
        {"title": "Let It Be", "artist": "The Beatles"},
        {"title": "Bridge Over Troubled Water", "artist": "Simon & Garfunkel"},
        {"title": "Creep", "artist": "Radiohead"},
    ],
    "달달한 노래": [
        # 한국 가요
        {"title": "Love Lee", "artist": "AKMU"},
        {"title": "선물", "artist": "멜로망스"},
        {"title": "벚꽃 엔딩", "artist": "장범준"},
        {"title": "우주를 줄게", "artist": "볼빨간사춘기"},
        {"title": "사랑은 늘 도망가", "artist": "임영웅"},
        {"title": "취중고백", "artist": "김민석"},
        {"title": "너의 의미", "artist": "아이유"},
        {"title": "아로하", "artist": "조정석"},
        {"title": "주저하는 연인들을 위해", "artist": "잔나비"},
        {"title": "두 사람", "artist": "성시경"},
        {"title": "좋아 좋아", "artist": "일기예보"},
        {"title": "다행이다", "artist": "이적"},
        # 팝송
        {"title": "Peaches", "artist": "Justin Bieber"},
        {"title": "Kiss Me More", "artist": "Doja Cat"},
        {"title": "Perfect", "artist": "Ed Sheeran"},
        {"title": "I'm Yours", "artist": "Jason Mraz"},
        {"title": "Just The Way You Are", "artist": "Bruno Mars"},
        {"title": "Double Take", "artist": "dhruv"},
        {"title": "At My Worst", "artist": "Pink Sweat$"},
        {"title": "Reality", "artist": "Jeff Bernat"},
    ],
    "운전할 때": [
        # 한국 가요
        {"title": "Hype Boy", "artist": "NewJeans"},
        {"title": "Seven", "artist": "정국"},
        {"title": "After LIKE", "artist": "아이브"},
        {"title": "건물 사이에 피어난 장미", "artist": "H1-KEY"},
        {"title": "Attention", "artist": "NewJeans"},
        {"title": "Love Dive", "artist": "아이브"},
        {"title": "Spicy", "artist": "aespa"},
        {"title": "뷰티풀", "artist": "크러쉬"},
        {"title": "Dolphin", "artist": "오마이걸"},
        {"title": "신호등", "artist": "이무진"},
        {"title": "Next Level", "artist": "aespa"},
        {"title": "View", "artist": "샤이니"},
        # 팝송
        {"title": "As It Was", "artist": "Harry Styles"},
        {"title": "Cruel Summer", "artist": "Taylor Swift"},
        {"title": "Stay", "artist": "The Kid LAROI"},
        {"title": "I Ain't Worried", "artist": "OneRepublic"},
        {"title": "Levitating", "artist": "Dua Lipa"},
        {"title": "Blinding Lights", "artist": "The Weeknd"},
        {"title": "Sunroof", "artist": "Nicky Youre"},
        {"title": "Watermelon Sugar", "artist": "Harry Styles"},
    ],
    "운동할 때": [
        # 한국 가요
        {"title": "Antifragile", "artist": "LE SSERAFIM"},
        {"title": "Super Shy", "artist": "NewJeans"},
        {"title": "손오공", "artist": "세븐틴"},
        {"title": "이브 프시케 그리고 푸른 수염의 아내", "artist": "LE SSERAFIM"},
        {"title": "Smoke", "artist": "다이나믹 듀오"},
        {"title": "특", "artist": "Stray Kids"},
        {"title": "Fast Forward", "artist": "전소미"},
        {"title": "Baggy Jeans", "artist": "NCT U"},
        {"title": "영웅", "artist": "NCT 127"},
        {"title": "ETA", "artist": "NewJeans"},
        {"title": "Baddie", "artist": "아이브"},
        {"title": "퀸카", "artist": "아이들"},
        # 팝송
        {"title": "Unholy", "artist": "Sam Smith"},
        {"title": "Flowers", "artist": "Miley Cyrus"},
        {"title": "Good 4 U", "artist": "Olivia Rodrigo"},
        {"title": "Industry Baby", "artist": "Lil Nas X"},
        {"title": "Bones", "artist": "Imagine Dragons"},
        {"title": "Physical", "artist": "Dua Lipa"},
        {"title": "Paint The Town Red", "artist": "Doja Cat"},
        {"title": "Believer", "artist": "Imagine Dragons"},
    ],
    "집중 할때": [
        # 한국 가요
        {"title": "밤편지", "artist": "아이유"},
        {"title": "비가 오는 날엔", "artist": "비스트"},
        {"title": "instagram", "artist": "DEAN"},
        {"title": "Rain", "artist": "태연"},
        {"title": "Square (2017)", "artist": "백예린"},
        {"title": "좋다고 말해", "artist": "볼빨간사춘기"},
        {"title": "와르르", "artist": "Colde"},
        {"title": "오래된 노래", "artist": "스탠딩 에그"},
        {"title": "금요일에 만나요", "artist": "아이유"},
        {"title": "커피한잔할래요", "artist": "폴킴"},
        {"title": "어떻게 이별까지 사랑하겠어", "artist": "AKMU"},
        {"title": "밤하늘의 별을", "artist": "경서"},
        # 팝송
        {"title": "comethru", "artist": "Jeremy Zucker"},
        {"title": "Paris in the Rain", "artist": "Lauv"},
        {"title": "Sunday Morning", "artist": "Maroon 5"},
        {"title": "Best Part", "artist": "Daniel Caesar"},
        {"title": "Don't Know Why", "artist": "Norah Jones"},
        {"title": "Put Your Records On", "artist": "Corinne Bailey Rae"},
        {"title": "Off My Face", "artist": "Justin Bieber"},
        {"title": "Youth", "artist": "Troye Sivan"},
    ],
    "이별 노래": [
        # 한국 가요
        {"title": "헤어지자 말해요", "artist": "박재정"},
        {"title": "보고 싶다", "artist": "김범수"},
        {"title": "좋니", "artist": "윤종신"},
        {"title": "어디에도", "artist": "엠씨더맥스"},
        {"title": "소주 한 잔", "artist": "임창정"},
        {"title": "체념", "artist": "빅마마"},
        {"title": "응급실", "artist": "izi"},
        {"title": "너를 만나", "artist": "폴킴"},
        {"title": "가시", "artist": "버즈"},
        {"title": "첫눈처럼 너에게 가겠다", "artist": "에일리"},
        {"title": "기억을 걷는 시간", "artist": "넬"},
        {"title": "사랑에 연습이 있었다면", "artist": "임재현"},
        # 팝송
        {"title": "Drivers License", "artist": "Olivia Rodrigo"},
        {"title": "Someone You Loved", "artist": "Lewis Capaldi"},
        {"title": "When I Was Your Man", "artist": "Bruno Mars"},
        {"title": "Stay With Me", "artist": "Sam Smith"},
        {"title": "Lose You To Love Me", "artist": "Selena Gomez"},
        {"title": "I'm Not The Only One", "artist": "Sam Smith"},
        {"title": "Un-Break My Heart", "artist": "Toni Braxton"},
        {"title": "Grenade", "artist": "Bruno Mars"},
    ],
    "잠 안 올때": [
        # 한국 가요
        {"title": "무릎", "artist": "아이유"},
        {"title": "스토커", "artist": "10CM"},
        {"title": "양화대교", "artist": "Zion.T"},
        {"title": "잘 자요", "artist": "Zion.T"},
        {"title": "서른 즈음에", "artist": "김광석"},
        {"title": "잊어야 한다는 마음으로", "artist": "김광석"},
        {"title": "12시 30분", "artist": "비스트"},
        {"title": "기억의 습작", "artist": "전람회"},
        {"title": "눈의 꽃", "artist": "박효신"},
        {"title": "거리에서", "artist": "성시경"},
        {"title": "바람기억", "artist": "나얼"},
        {"title": "미안해 널 미워해", "artist": "자우림"},
        # 팝송
        {"title": "pov", "artist": "Ariana Grande"},
        {"title": "Chandelier (Piano Ver.)", "artist": "Sia"},
        {"title": "All of Me", "artist": "John Legend"},
        {"title": "2002", "artist": "Anne-Marie"},
        {"title": "Thinking Out Loud", "artist": "Ed Sheeran"},
        {"title": "Honesty", "artist": "Pink Sweat$"},
        {"title": "City of Stars", "artist": "Ryan Gosling"},
        {"title": "Lost Stars", "artist": "Adam Levine"},
    ],
}

# 2. 장르 별 스테이션 (신규 데이터)
GENRE_STATIONS = {
    "요즘 K-POP": [
        {"title": "Whiplash", "artist": "aespa"},
        {"title": "Love, Money, Fame", "artist": "세븐틴"},
        {"title": "Cherish", "artist": "ILLIT"},
        {"title": "Gold", "artist": "ITZY"},
        {"title": "Mantra", "artist": "제니"},
        {"title": "Moonlit Floor", "artist": "리사"},
        {"title": "UP", "artist": "카리나"},
        {"title": "Power", "artist": "지드래곤"},
        {"title": "APT.", "artist": "로제"},
        {"title": "Steady", "artist": "NCT WISH"},
        {"title": "SOS", "artist": "피프티 피프티"},
        {"title": "Pleasure", "artist": "강다니엘"},
    ],
    "요즘 POP": [
        {"title": "Die With A Smile", "artist": "Lady Gaga"},
        {"title": "Birds of a Feather", "artist": "Billie Eilish"},
        {"title": "Espresso", "artist": "Sabrina Carpenter"},
        {"title": "Taste", "artist": "Sabrina Carpenter"},
        {"title": "Good Luck, Babe!", "artist": "Chappell Roan"},
        {"title": "Dancing in the Flames", "artist": "The Weeknd"},
        {"title": "Disease", "artist": "Lady Gaga"},
        {"title": "Stargazing", "artist": "Myles Smith"},
    ],
    "슬픈 발라드": [
        {"title": "헤어지자 말해요", "artist": "박재정"},
        {"title": "인사", "artist": "범진"},
        {"title": "너의 모든 순간", "artist": "성시경"},
        {"title": "온기", "artist": "임영웅"},
        {"title": "첫 눈", "artist": "EXO"},
        {"title": "일기", "artist": "김나영"},
        {"title": "너를 만나", "artist": "폴킴"},
        {"title": "어떻게 이별까지 사랑하겠어", "artist": "AKMU"},
        {"title": "사막에서 꽃을 피우듯", "artist": "우디"},
        {"title": "모래 알갱이", "artist": "임영웅"},
        {"title": "만남은 쉽고 이별은 어려워", "artist": "베이식"},
        {"title": "그리워하다", "artist": "비투비"},
    ],
    "편안한 알앤비": [
        {"title": "instagram", "artist": "DEAN"},
        {"title": "Bye bye my blue", "artist": "백예린"},
        {"title": "어색하게", "artist": "박재범"},
        {"title": "가끔", "artist": "크러쉬"},
        {"title": "주마등", "artist": "빈지노"},
        {"title": "비", "artist": "폴킴"},
        {"title": "Blue", "artist": "태형"},
        {"title": "오랜만이야", "artist": "로꼬"},
        {"title": "우주를 건너", "artist": "백예린"},
        {"title": "D (Half Moon)", "artist": "DEAN"},
        {"title": "잊어버리지마", "artist": "크러쉬"},
        {"title": "Hype Boy (R&B Ver.)", "artist": "뉴진스"},
    ],
    "요즘 국힙": [
        {"title": "Small girl", "artist": "이영지"},
        {"title": "미안해", "artist": "양홍원"},
        {"title": "응", "artist": "그루비룸"},
        {"title": "Burn It", "artist": "블라세"},
        {"title": "가시", "artist": "창모"},
        {"title": "DNA", "artist": "박재범"},
        {"title": "빙글빙글", "artist": "헤이즈"},
        {"title": "Break", "artist": "빈지노"},
        {"title": "Counting Stars", "artist": "비오"},
        {"title": "고독하구만", "artist": "머쉬베놈"},
        {"title": "눈", "artist": "자이언티"},
        {"title": "호우주의보", "artist": "창모"},
    ],
    "요즘 외힙": [
        {"title": "Not Like Us", "artist": "Kendrick Lamar"},
        {"title": "Timeless", "artist": "The Weeknd"},
        {"title": "Like That", "artist": "Future"},
        {"title": "Million Dollar Baby", "artist": "Tommy Richman"},
        {"title": "Carnival", "artist": "Kanye West"},
        {"title": "Type Shit", "artist": "Future"},
        {"title": "FE!N", "artist": "Travis Scott"},
        {"title": "Rockstar", "artist": "Post Malone"},
    ],
    "잔잔한 클래식": [
        {"title": "River Flows In You", "artist": "이루마"},
        {"title": "Gymnopédie No. 1", "artist": "Erik Satie"},
        {"title": "Clair de Lune", "artist": "Debussy"},
        {"title": "Nocturne Op. 9 No. 2", "artist": "Chopin"},
        {"title": "Canon in D", "artist": "Pachelbel"},
        {"title": "The Swan", "artist": "Saint-Saëns"},
        {"title": "Air on the G String", "artist": "Bach"},
        {"title": "Liebestraum No. 3", "artist": "Liszt"},
        {"title": "Pavane", "artist": "Fauré"},
        {"title": "Merry-Go-Round of Life", "artist": "Joe Hisaishi"},
        {"title": "Summer", "artist": "Joe Hisaishi"},
        {"title": "Serenade", "artist": "Schubert"},
    ],
    "EDM": [
        {"title": "The Spectre", "artist": "Alan Walker"},
        {"title": "Wake Me Up", "artist": "Avicii"},
        {"title": "Stay", "artist": "Zedd"},
        {"title": "Clarity", "artist": "Zedd"},
        {"title": "Heroes", "artist": "Alesso"},
        {"title": "Don't Let Me Down", "artist": "The Chainsmokers"},
        {"title": "Animals", "artist": "Martin Garrix"},
        {"title": "Titanium", "artist": "David Guetta"},
        {"title": "Levels", "artist": "Avicii"},
        {"title": "Starboy", "artist": "The Weeknd"},
        {"title": "Lean On", "artist": "Major Lazer"},
    ],
}

# 3. 통합 데이터 (구조화)
STATION_DATA = {
    "mood": MOOD_STATIONS,
    "genre": GENRE_STATIONS
}

# 하위 호환성을 위해 기존 이름도 남겨둠 (필요시 사용)
# STATION_CURATION = {**MOOD_STATIONS, **GENRE_STATIONS} 
