# Generated by Django 4.2.27 on 2026-01-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            # 칼럼 추가
            sql="""
            ALTER TABLE artists 
            ADD COLUMN IF NOT EXISTS image_square VARCHAR(500),
            ADD COLUMN IF NOT EXISTS image_circle_1 VARCHAR(500),
            ADD COLUMN IF NOT EXISTS image_circle_2 VARCHAR(500);
            """,
            # 롤백 SQL (필요시)
            reverse_sql="""
            ALTER TABLE artists 
            DROP COLUMN IF EXISTS image_square,
            DROP COLUMN IF EXISTS image_circle_1,
            DROP COLUMN IF EXISTS image_circle_2;
            """
        ),
    ]
