# Generated by Django 4.2.27 on 2026-01-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_add_artist_image_columns'),
    ]

    operations = [
        migrations.RunSQL(
            # 칼럼 이름 변경
            sql="""
            ALTER TABLE artists 
            RENAME COLUMN image_circle_1 TO image_small_circle;
            
            ALTER TABLE artists 
            RENAME COLUMN image_circle_2 TO image_large_circle;
            """,
            # 롤백 SQL
            reverse_sql="""
            ALTER TABLE artists 
            RENAME COLUMN image_small_circle TO image_circle_1;
            
            ALTER TABLE artists 
            RENAME COLUMN image_large_circle TO image_circle_2;
            """
        ),
    ]
