# Generated by Django 4.2.27 on 2026-01-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_artist_circle_columns'),
    ]

    operations = [
        migrations.RunSQL(
            # 칼럼 추가
            sql="""
            ALTER TABLE albums 
            ADD COLUMN IF NOT EXISTS image_square VARCHAR(500);
            """,
            # 롤백 SQL
            reverse_sql="""
            ALTER TABLE albums 
            DROP COLUMN IF EXISTS image_square;
            """
        ),
    ]
