AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  이미지 리사이징 Lambda 함수 (기존 S3 버킷 사용)
  기존 S3 버킷에 이미지 업로드 시 자동으로 리사이징합니다.

# 글로벌 설정
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11
    Architectures:
      - x86_64

# 파라미터 (배포 시 입력)
Parameters:
  ExistingBucketName:
    Type: String
    Description: 기존 S3 버킷 이름 (이미 존재하는 버킷)

Resources:
  # Lambda 함수 정의
  ImageResizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: music-image-resizer
      Description: 아티스트/앨범/트랙 이미지 리사이징 (기존 버킷 사용)
      CodeUri: image_resizer/
      Handler: app.lambda_handler
      
      # 환경 변수
      Environment:
        Variables:
          BUCKET_NAME: !Ref ExistingBucketName
      
      # IAM 정책 - S3 읽기/쓰기 권한
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource: !Sub 'arn:aws:s3:::${ExistingBucketName}/*'
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: !Sub 'arn:aws:s3:::${ExistingBucketName}'

# 출력
Outputs:
  ImageResizerFunction:
    Description: Lambda 함수 ARN
    Value: !GetAtt ImageResizerFunction.Arn
  
  ImageResizerFunctionName:
    Description: Lambda 함수 이름
    Value: !Ref ImageResizerFunction
  
  SetupInstructions:
    Description: S3 트리거 설정 안내
    Value: |
      기존 버킷을 사용하므로 S3 트리거를 AWS Console에서 수동으로 설정해야 합니다.
      
      1. AWS Console > S3 > 버킷 선택
      2. Properties > Event notifications > Create event notification
      3. 다음 경로에 대해 각각 이벤트 생성:
         - media/images/artists/original/
         - media/images/albums/original/
         - media/images/tracks/original/
      4. Event types: s3:ObjectCreated:*
      5. Destination: Lambda function > music-image-resizer
